(() => {
  const labels = {
    ja:{login:'ログイン',signup:'新規登録',logout:'ログアウト',email:'メールアドレス',password:'パスワード',credits:'クレジット',free:'無料',standard:'Standard',pro:'Pro',buy:'プランを変更',close:'閉じる',needAuth:'ログインするとクレジットを安全に管理できます。',sent:'確認メールを送信しました。',wrong:'メールアドレスまたはパスワードを確認してください。'},
    en:{login:'Log in',signup:'Sign up',logout:'Log out',email:'Email',password:'Password',credits:'Credits',free:'Free',standard:'Standard',pro:'Pro',buy:'Change plan',close:'Close',needAuth:'Log in to securely manage your credits.',sent:'Confirmation email sent.',wrong:'Check your email and password.'},
    ko:{login:'로그인',signup:'가입',logout:'로그아웃',email:'이메일',password:'비밀번호',credits:'크레딧',free:'무료',standard:'Standard',pro:'Pro',buy:'플랜 변경',close:'닫기',needAuth:'로그인하면 크레딧을 안전하게 관리할 수 있습니다.',sent:'확인 이메일을 보냈습니다.',wrong:'이메일과 비밀번호를 확인하세요.'},
    'zh-CN':{login:'登录',signup:'注册',logout:'退出',email:'邮箱',password:'密码',credits:'积分',free:'免费',standard:'Standard',pro:'Pro',buy:'更改方案',close:'关闭',needAuth:'登录后即可安全管理积分。',sent:'确认邮件已发送。',wrong:'请检查邮箱和密码。'},
    'zh-TW':{login:'登入',signup:'註冊',logout:'登出',email:'電子郵件',password:'密碼',credits:'點數',free:'免費',standard:'Standard',pro:'Pro',buy:'變更方案',close:'關閉',needAuth:'登入後即可安全管理點數。',sent:'確認郵件已寄出。',wrong:'請確認電子郵件與密碼。'}
  };
  let supabase = null, current = null;
  const locale = () => (localStorage.getItem('iconia_locale') || navigator.language || 'ja').toLowerCase().startsWith('en') ? 'en' : (localStorage.getItem('iconia_locale') || 'ja');
  const t = () => labels[locale()] || labels.ja;
  const style = `#accountBtn{position:fixed;left:12px;top:12px;z-index:10000;background:#151822;color:#fff;border:1px solid #34394b;border-radius:12px;padding:9px 12px;font:700 12px -apple-system,BlinkMacSystemFont,sans-serif}#accountPanel{display:none;position:fixed;left:12px;top:56px;z-index:10001;width:290px;background:#11131b;color:#f5f6fa;border:1px solid #34394b;border-radius:16px;padding:16px;box-shadow:0 18px 50px #000b;font:14px -apple-system,BlinkMacSystemFont,sans-serif}#accountPanel input{width:100%;box-sizing:border-box;margin:6px 0;padding:11px;border-radius:10px;border:1px solid #34394b;background:#080a10;color:#fff}#accountPanel button{border:0;border-radius:10px;padding:10px 12px;margin:4px 3px 4px 0;font-weight:700}#accountPanel .primary{background:#fff;color:#080a10}#accountPanel .plan{display:flex;justify-content:space-between;align-items:center;padding:9px 0;border-top:1px solid #292d3a}#accountPanel small{opacity:.7}`;
  function el(tag, attrs={}, text=''){const e=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));e.textContent=text;return e;}
  function render(){
    const old=document.getElementById('accountPanel'); if(old) old.remove();
    const panel=el('div',{id:'accountPanel'}), L=t();
    if(!current){ panel.append(el('div',{},L.needAuth)); const email=el('input',{id:'accEmail',type:'email',placeholder:L.email}); const pass=el('input',{id:'accPass',type:'password',placeholder:L.password}); panel.append(email,pass); const login=el('button',{class:'primary'},L.login); const signup=el('button',{},L.signup); panel.append(login,signup); login.onclick=()=>auth('login'); signup.onclick=()=>auth('signup'); }
    else { panel.append(el('div',{},current.email||'')); panel.append(el('div',{id:'accStatus'},'Loading…')); const plans=el('div'); [['standard',540],['pro',1620]].forEach(([id,price])=>{const row=el('div',{class:'plan'});row.append(el('span',{},`${L[id]} ¥${price}/月`));const b=el('button',{},L.buy);b.onclick=()=>checkout(id);row.append(b);plans.append(row)});panel.append(plans);const out=el('button',{},L.logout);out.onclick=async()=>{await supabase.auth.signOut();current=null;render();};panel.append(out);loadAccount();}
    const close=el('button',{},L.close);close.onclick=()=>panel.style.display='none';panel.append(close);document.body.append(panel);
  }
  async function auth(mode){const email=document.getElementById('accEmail')?.value.trim(),password=document.getElementById('accPass')?.value;if(!email||!password)return;const r=mode==='signup'?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error){alert(t().wrong);return;}if(mode==='signup'&&!r.data.session){alert(t().sent);return;}current=r.data.user;render();}
  async function loadAccount(){const {data:{session}}=await supabase.auth.getSession();if(!session)return;const r=await fetch('/api/account',{headers:{Authorization:`Bearer ${session.access_token}`}});if(r.ok){const d=await r.json();const a=d.account;document.getElementById('accStatus').textContent=`${a.plan} · ${t().credits}: ${a.credits}`;}}
  async function checkout(plan){const {data:{session}}=await supabase.auth.getSession();if(!session){render();return;}const r=await fetch('/api/billing/checkout',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({plan})});const d=await r.json();if(d.url)location.href=d.url;else alert(d.error||'Checkout failed');}
  async function init(){const r=await fetch('/api/config');if(!r.ok)return;const cfg=await r.json();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=async()=>{supabase=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);const {data}=await supabase.auth.getSession();current=data.session?.user||null;window.iconiaGetAccessToken=async()=>{const x=await supabase.auth.getSession();return x.data.session?.access_token||''};supabase.auth.onAuthStateChange((_e,session)=>{current=session?.user||null;render();});render();};document.head.appendChild(s);}
  const btn=el('button',{id:'accountBtn'},t().login);btn.onclick=()=>{const p=document.getElementById('accountPanel');if(p)p.style.display=p.style.display==='block'?'none':'block';else{render();document.getElementById('accountPanel').style.display='block';}};document.head.appendChild(el('style',{},style));document.body.append(btn);init();
})();
