/* Iconia AI multilingual UI + API locale bridge: JA / EN / KO / zh-CN / zh-TW */
const ICONIA_LOCALES={
ja:{name:'日本語',dir:'ltr',title:'Iconia AI — 高精度ゲームアイコンAI',tagline:'話すだけで、理想のゲームアイコンを。',history:'履歴',newChat:'新しい会話',newChatSide:'＋ 新しい会話',recent:'最近の会話',reset:'会話をリセット',outputSize:'出力サイズ',icon:'🎮 ゲームアイコン 1:1',xheader:'𝕏 X / Twitter 3:1',youtube:'▶ YouTube 16:9',portrait:'▯ 縦長 2:3',mode:'編集モード',auto:'自動・高精度',identity:'同一性を最優先',partial:'部分編集',text:'文字・ロゴ',style:'絵柄だけ変更',background:'背景だけ変更',placeholder:'作りたい画像を自由に説明してください…',attach:'参考画像',attachHint:'この画像を元に編集します',historyTitle:'会話履歴',thinking:'考えています…',creating:'作成中…',finishing:'仕上げています…',saveHint:'画像を長押しして「写真に保存」を選択してください。',lineBreak:'Enter＝改行 ／ ⌘+Enter・Ctrl+Enter＝送信'},
en:{name:'English',dir:'ltr',title:'Iconia AI — High-Precision Gaming Icon AI',tagline:'Create your perfect gaming icon by simply chatting.',history:'History',newChat:'New chat',newChatSide:'＋ New chat',recent:'Recent chats',reset:'Reset chat',outputSize:'Output size',icon:'🎮 Gaming icon 1:1',xheader:'𝕏 X / Twitter 3:1',youtube:'▶ YouTube 16:9',portrait:'▯ Portrait 2:3',mode:'Edit mode',auto:'Auto · High precision',identity:'Identity first',partial:'Targeted edit',text:'Text · Logo',style:'Style only',background:'Background only',placeholder:'Describe the image you want…',attach:'Reference image',attachHint:'Edit from this image',historyTitle:'Conversation history',thinking:'Thinking…',creating:'Creating…',finishing:'Finishing…',saveHint:'Press and hold the image, then choose “Save to Photos”.',lineBreak:'Enter = new line · ⌘+Enter / Ctrl+Enter = send'},
ko:{name:'한국어',dir:'ltr',title:'Iconia AI — 고정밀 게임 아이콘 AI',tagline:'대화만으로 나만의 게임 아이콘을 만들어 보세요.',history:'기록',newChat:'새 대화',newChatSide:'＋ 새 대화',recent:'최근 대화',reset:'대화 초기화',outputSize:'출력 크기',icon:'🎮 게임 아이콘 1:1',xheader:'𝕏 X / Twitter 3:1',youtube:'▶ YouTube 16:9',portrait:'▯ 세로형 2:3',mode:'편집 모드',auto:'자동 · 고정밀',identity:'캐릭터 동일성 우선',partial:'부분 편집',text:'텍스트 · 로고',style:'화풍만 변경',background:'배경만 변경',placeholder:'원하는 이미지를 자유롭게 설명해 주세요…',attach:'참조 이미지',attachHint:'이 이미지를 기준으로 편집합니다',historyTitle:'대화 기록',thinking:'생각하는 중…',creating:'생성 중…',finishing:'마무리 중…',saveHint:'이미지를 길게 누른 후 “사진에 저장”을 선택하세요.',lineBreak:'Enter = 줄바꿈 · ⌘+Enter / Ctrl+Enter = 전송'},
'zh-CN':{name:'简体中文',dir:'ltr',title:'Iconia AI — 高精度游戏头像 AI',tagline:'只需聊天，就能制作专属游戏头像。',history:'历史记录',newChat:'新对话',newChatSide:'＋ 新对话',recent:'最近对话',reset:'重置对话',outputSize:'输出尺寸',icon:'🎮 游戏头像 1:1',xheader:'𝕏 X / Twitter 3:1',youtube:'▶ YouTube 16:9',portrait:'▯ 竖版 2:3',mode:'编辑模式',auto:'自动 · 高精度',identity:'优先保持人物一致',partial:'局部编辑',text:'文字 · Logo',style:'仅修改画风',background:'仅修改背景',placeholder:'自由描述你想制作的图片…',attach:'参考图片',attachHint:'以这张图片为基础编辑',historyTitle:'对话历史',thinking:'思考中…',creating:'制作中…',finishing:'完善中…',saveHint:'长按图片，然后选择“存储到照片”。',lineBreak:'Enter = 换行 · ⌘+Enter / Ctrl+Enter = 发送'},
'zh-TW':{name:'繁體中文',dir:'ltr',title:'Iconia AI — 高精度遊戲頭像 AI',tagline:'只要聊天，就能製作專屬遊戲頭像。',history:'歷史紀錄',newChat:'新對話',newChatSide:'＋ 新對話',recent:'最近對話',reset:'重設對話',outputSize:'輸出尺寸',icon:'🎮 遊戲頭像 1:1',xheader:'𝕏 X / Twitter 3:1',youtube:'▶ YouTube 16:9',portrait:'▯ 直式 2:3',mode:'編輯模式',auto:'自動 · 高精度',identity:'優先保持人物一致',partial:'局部編輯',text:'文字 · Logo',style:'僅修改畫風',background:'僅修改背景',placeholder:'自由描述你想製作的圖片…',attach:'參考圖片',attachHint:'以這張圖片為基礎編輯',historyTitle:'對話歷史',thinking:'正在思考…',creating:'正在製作…',finishing:'正在完善…',saveHint:'長按圖片，然後選擇「儲存到照片」。',lineBreak:'Enter = 換行 · ⌘+Enter / Ctrl+Enter = 傳送'}
};
function detectIconiaLocale(navigatorLanguage=navigator.language||'ja-JP'){const saved=localStorage.getItem('iconia_locale');if(saved&&ICONIA_LOCALES[saved])return saved;const l=String(navigatorLanguage||'').toLowerCase();if(l.startsWith('ko'))return'ko';if(l.startsWith('zh-tw')||l.startsWith('zh-hk')||l.startsWith('zh-mo'))return'zh-TW';if(l.startsWith('zh'))return'zh-CN';if(l.startsWith('en'))return'en';return'ja'}
let iconiaLocale=detectIconiaLocale();
window.iconiaLocale=()=>iconiaLocale;window.iconiaT=()=>ICONIA_LOCALES[iconiaLocale];
function applyIconiaI18n(){const t=ICONIA_LOCALES[iconiaLocale];document.documentElement.lang=iconiaLocale;document.title=t.title;const byId={historyBtn:'history',newBtn:'newChat',sideNew:'newChatSide',sideHistory:'recent',clearBtn:'reset'};Object.entries(byId).forEach(([id,k])=>{const e=document.getElementById(id);if(e)e.textContent=t[k]});const labels=document.querySelectorAll('.label');if(labels[0])labels[0].textContent=t.outputSize;if(labels[1])labels[1].textContent=t.mode;const ta=document.getElementById('text');if(ta)ta.placeholder=t.placeholder;const hint=document.querySelector('.hint');if(hint)hint.textContent=t.lineBreak;document.querySelectorAll('[data-format]').forEach(b=>b.textContent=t[b.dataset.format]);document.querySelectorAll('[data-mode]').forEach(b=>{const k=b.dataset.mode==='text'?'text':b.dataset.mode;if(t[k])b.textContent=t[k]});document.querySelectorAll('.attachInfo b').forEach(e=>e.textContent=t.attach);document.querySelectorAll('.attachInfo small').forEach(e=>e.textContent=t.attachHint);document.querySelectorAll('.saveHint').forEach(e=>e.textContent=t.saveHint);let s=document.getElementById('localeSelector');if(!s){s=document.createElement('select');s.id='localeSelector';s.className='headBtn';s.setAttribute('aria-label','Language');document.querySelector('.actions')?.prepend(s);s.onchange=()=>{iconiaLocale=s.value;localStorage.setItem('iconia_locale',iconiaLocale);applyIconiaI18n();if(typeof render==='function')render()}}s.innerHTML=Object.entries(ICONIA_LOCALES).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join('');s.value=iconiaLocale}
const nativeFetch=window.fetch;window.fetch=async function(input,init={}){try{const url=typeof input==='string'?input:input?.url;if(url&&url.includes('/api/generate')&&init.body){const p=JSON.parse(init.body);p.locale=iconiaLocale;init={...init,body:JSON.stringify(p)}}}catch{}return nativeFetch(input,init)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',applyIconiaI18n);else applyIconiaI18n();
