import OpenAI, { toFile } from "openai";
const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
const PLANNER_MODEL="gpt-5.6";
const IMAGE_MODEL="gpt-image-2";
const clean=(v,n=12000)=>String(v??"").trim().slice(0,n);
function imageBuffer(u){const m=String(u||"").match(/^data:image\/[^;]+;base64,(.+)$/);if(!m)throw Error("画像データを読み込めませんでした。");return Buffer.from(m[1],"base64")}
function size(t){t=String(t||"").toLowerCase();if(/ヘッダー|header|banner|バナー|横長|twitter|xのヘッダー/.test(t))return"1536x1024";if(/縦長|portrait|story|ストーリー|tiktok/.test(t))return"1024x1536";return"1024x1024"}
function exact(t){t=String(t||"").trim();if(!t)return null;let ms=[...t.matchAll(/[「『“"]([^」』”"]{1,100})[」』”"]/gu)];if(ms.length)return ms.map(m=>m[1].trim()).filter(Boolean).join("\n");let m=t.match(/(?:文字|テキスト|ロゴ|名前|チーム名|クラン名|同盟名|ギルド名)\s*(?:は|を|：|:)\s*[「『“"]?([^」』”"\n]{1,80})/u);if(m)return m[1].trim();m=t.match(/([A-Za-z][A-Za-z0-9._-]{0,50})\s*(?:の|という)\s*(?:文字|テキスト|ロゴ)/i);if(m)return m[1].trim();m=t.match(/([A-Za-z][A-Za-z0-9._-]{0,50})\s*(?:を|って)\s*(?:入れて|追加して|加えて|書いて|載せて)/i);if(m)return m[1].trim();return null}
function fallbackMode(t,img){if(!img)return"ORIGINAL";if(/文字だけ|テキストだけ|ロゴだけ/.test(t))return"TEXT_ONLY";if(/イラストタッチ|絵柄|画風|タッチ|作画|アートスタイル|絵の感じ|テイスト|style transfer/i.test(t))return"STYLE_ONLY";if(/背景だけ|背景のみ/.test(t))return"BACKGROUND_ONLY";if(/ポーズだけ|ポーズのみ/.test(t))return"POSE_ONLY";if(/髪だけ|髪型だけ|髪のみ/.test(t))return"HAIR_ONLY";if(/服だけ|衣装だけ|服装だけ/.test(t))return"CLOTHING_ONLY";if(/そのまま|原画維持|原型を残/.test(t))return"FAITHFUL";return"TARGETED_EDIT"}
function parse(t){t=String(t||"").trim().replace(/^```json\s*/i,"").replace(/\s*```$/i,"");try{return JSON.parse(t)}catch{}let a=t.indexOf("{"),b=t.lastIndexOf("}");if(a>=0&&b>a)try{return JSON.parse(t.slice(a,b+1))}catch{}return null}
async function plan({message,image,history}){const recent=(Array.isArray(history)?history.slice(-18):[]).map((m,i)=>`${i+1}. ${m.role==="user"?"USER":"ASSISTANT"}: ${clean(m.text,1400)}`).join("\n");const instructions=`You are Iconia AI's expert reasoning layer for premium game/SNS image creation and editing. Understand the whole conversation and reference image before planning. Resolve references such as これ, さっきの, 前の画像, このキャラ, もっと, そのまま, 同じ人, 同じキャラ. Never treat the latest sentence as isolated.
IDENTITY LOCK: when a reference image exists, it is the source of truth. Preserve the same person/character identity unless explicitly asked to replace it. Lock face shape, facial landmarks, eyes, nose, mouth, expression, hairstyle, hair color, skin tone, body proportions, clothing, accessories, distinctive marks, pose, camera angle, crop, composition and background.
STYLE-ONLY HARD RULE: if the user asks only to change illustration style/touch/絵柄/画風, use STYLE_ONLY. The output must depict the SAME source image and SAME subject, not a new character. Preserve exact identity, face, hair, outfit, pose, camera, crop, composition, background and logo placement. Change only linework, brush texture, shading, rendering, color treatment and illustration finish.
TARGETED EDIT RULE: change only what the user requests and preserve everything else. "もっとかっこよく/可愛く/おしゃれに" applies only to the requested element.
TEXT RULE: exact user text must be preserved character-for-character. If only adding text/logo/name, use TEXT_ONLY. Full logo redesign or overall composition redesign may use AI_DESIGN.
QUALITY RULE: premium game icon, polished anatomy, clean silhouette, strong focal point, cinematic readable lighting, high detail, no watermarks, no invented words.
Return ONLY JSON: {"mode":"ORIGINAL|FAITHFUL|STYLE_ONLY|TARGETED_EDIT|AI_DESIGN|BACKGROUND_ONLY|POSE_ONLY|HAIR_ONLY|CLOTHING_ONLY|TEXT_ONLY","requested_text":string|null,"text_position":string|null,"identity_lock":[string],"keep":[string],"change":[string],"style":"string","composition":"string","image_prompt":"string","assistant_reply":"string"}`;const content=[{type:"input_text",text:`LATEST USER REQUEST:\n${clean(message)}\n\nRECENT CONVERSATION:\n${recent||"none"}\n\nREFERENCE IMAGE: ${image?"YES":"NO"}`}];if(image)content.push({type:"input_image",image_url:image,detail:"high"});const r=await client.responses.create({model:PLANNER_MODEL,input:[{role:"developer",content:instructions},{role:"user",content}],max_output_tokens:2400});return parse(r.output_text)}
function normalize(p,t,img,force){let mode=String(p?.mode||fallbackMode(t,img)).toUpperCase();const ok=["ORIGINAL","FAITHFUL","STYLE_ONLY","TARGETED_EDIT","AI_DESIGN","BACKGROUND_ONLY","POSE_ONLY","HAIR_ONLY","CLOTHING_ONLY","TEXT_ONLY"];if(!ok.includes(mode))mode=fallbackMode(t,img);if(force&&img&&!/文字だけ|テキストだけ|ロゴだけ/.test(t))mode="AI_DESIGN";const text=clean(p?.requested_text||exact(t),120)||null;let lock=Array.isArray(p?.identity_lock)?p.identity_lock:[],keep=Array.isArray(p?.keep)?p.keep:[],change=Array.isArray(p?.change)?p.change:[];if(mode==="STYLE_ONLY"){lock=[...lock,"SAME PERSON/CHARACTER IDENTITY","same face and facial landmarks","same eyes, nose, mouth and expression","same hairstyle and hair color","same skin tone and body proportions","same clothing and accessories","same pose and camera angle","same crop and composition","same background and distinctive objects","same logo/text placement"];change=[...change,"ONLY rendering style: linework, brushwork, shading, lighting, color rendering and finish"]}return{mode,requestedText:text,textPosition:clean(p?.text_position||"",100)||null,identityLock:[...new Set(lock.map(x=>clean(x,600)).filter(Boolean))],keep:[...new Set(keep.map(x=>clean(x,600)).filter(Boolean))],change:[...new Set(change.map(x=>clean(x,700)).filter(Boolean))],style:clean(p?.style||"premium polished game illustration",1800),composition:clean(p?.composition||"Preserve the reference composition unless explicitly changed.",1800),imagePrompt:clean(p?.image_prompt||t,10000),reply:clean(p?.assistant_reply||"できました。気になるところがあれば、そのまま続けて指示してください。",500)}}
function imagePrompt(p,t){const lock=p.identityLock.length?`\nIDENTITY LOCK — DO NOT CHANGE:\n- ${p.identityLock.join("\n- ")}`:"";const keep=p.keep.length?`\nKEEP EXACTLY:\n- ${p.keep.join("\n- ")}`:"";const change=p.change.length?`\nCHANGE ONLY:\n- ${p.change.join("\n- ")}`:"";const txt=p.requestedText?`\nEXACT TEXT: ${p.requestedText}\nPreserve exact spelling/case. Do not invent additional lettering.`:"";const pos=p.textPosition?`\nTEXT POSITION: ${p.textPosition}\nRespect the requested placement precisely.`:"";const style=p.mode==="STYLE_ONLY"?`\nSTYLE TRANSFER HARD LOCK:\nTreat the reference as the exact composition blueprint. Do NOT redesign, reinterpret, replace, beautify, reposition or invent the subject. The output should be recognizable as the same image immediately. Preserve the same face, eyes, hair, clothes, body, pose, camera angle, crop, background and all existing text/logo placement. Change ONLY the visual rendering style.`:"";return`Iconia AI image production. Follow the plan exactly.\nUSER REQUEST:\n${clean(t)}\nMODE: ${p.mode}\n\nAI PLAN:\n${p.imagePrompt}\n\nSTYLE:\n${p.style}\n\nCOMPOSITION:\n${p.composition}${lock}${keep}${change}${txt}${pos}${style}\n\nGLOBAL RULES:\n- Reference image is the primary source when present.\n- Never silently replace the subject or change identity.\n- Never invent watermarks, signatures, usernames or extra words.\n- Make requested changes visible but preserve everything else.\n- Premium game/SNS icon quality, strong focal point, clean silhouette, readable at small size, coherent anatomy and lighting.`}
export default async function handler(req,res){if(req.method!=="POST")return res.status(405).json({success:false,error:"POSTリクエストのみ対応しています。"});try{if(!process.env.OPENAI_API_KEY)return res.status(500).json({success:false,error:"OPENAI_API_KEY がVercelに設定されていません。"});const b=req.body||{},message=clean(b.message),image=typeof b.image==="string"&&b.image.startsWith("data:image/")?b.image:null,history=Array.isArray(b.history)?b.history:[],force=b.aiDesign===true;if(!message&&!image)return res.status(400).json({success:false,error:"画像またはメッセージを入力してください。"});let raw=await plan({message,image,history});if(!raw)raw={};const p=normalize(raw,message,Boolean(image),force);if(image&&p.mode==="TEXT_ONLY"&&p.requestedText)return res.status(200).json({success:true,image,overlay:{text:p.requestedText,message,design:p.style,position:p.textPosition},reply:`できました。「${p.requestedText.replace(/\n/g," / ")}」を元画像に追加します。`});const quality=(/高品質|高画質|最高|超高精細|精密|最高品質/i.test(message)||p.mode==="STYLE_ONLY")?"high":"medium";const prompt=imagePrompt(p,message);let out;if(image){const file=await toFile(imageBuffer(image),"reference.jpg",{type:"image/jpeg"});const params={model:IMAGE_MODEL,image:file,prompt,size:size(message),quality,output_format:"jpeg",output_compression:70,n:1};const r=await client.images.edit(params),b64=r?.data?.[0]?.b64_json;if(!b64)throw Error("画像データがOpenAIから返されませんでした。");out=Buffer.from(b64,"base64")}else{const r=await client.images.generate({model:IMAGE_MODEL,prompt,size:size(message),quality,output_format:"jpeg",output_compression:70,n:1}),b64=r?.data?.[0]?.b64_json;if(!b64)throw Error("画像データがOpenAIから返されませんでした。");out=Buffer.from(b64,"base64")}return res.status(200).json({success:true,image:`data:image/jpeg;base64,${out.toString("base64")}`,reply:p.reply,plan:{mode:p.mode,identityLock:p.identityLock}})}catch(e){console.error("ICONIA API ERROR",e);return res.status(Number(e?.status)||500).json({success:false,error:e?.error?.message||e?.message||"不明なエラーが発生しました。",code:e?.error?.code||e?.code||null,type:e?.error?.type||e?.type||null})}}